-- 코드를 입력하세요
SELECT *
FROM(
    /*SELECT COUNT(SCHEDULED_AT) AS COUNT,ROUND(SUM(PRICE)*0.1,0) AS INCENTIVE,PRICE,SCHEDULED_AT*/
    SELECT SCHEDULED_AT,ROUND(SUM(PRICE)*0.1,0) AS INCENTIVE
    FROM SCHEDULES
    GROUP BY SCHEDULED_AT
    HAVING COUNT(SCHEDULED_AT) >= 3
) SQ1
/*HAVING COUNT(SCEDULED_AT) >= 3*/