/*
join문에서 에러남...
*/
SELECT CART_PRODUCTS.NAME, COUNT(*) AS USER_COUNT
FROM JOIN CART ON CART.ID = CART_PRODUCTS.CART_ID
GROUP BY CART_PRODUCTS.NAME,CART.USER_ID
ORDER BY COUNT(*) DESC, CART_PRODUCTS.NAME ASC