-- 코드를 입력하세요
/*과일로 만든 아이스크림 고르기*/
SELECT A.FLAVOR
FROM FIRST_HALF A JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
WHERE B.INGREDIENT_TYPE LIKE "fruit%" AND A.TOTAL_ORDER >= 3000
ORDER BY A.TOTAL_ORDER DESC